### ISSUE TITLE
erro simples de digitação

### ISSUE THREAD

**Issue by dieguesmosken** [GilmarAlves99/Pariquera#1]
meu feedback: na parte do rodapé você escreveu seu email com @gmail.com.com
ouve uma repetição no .com
`<div class="caixa-g-5 caixa-m-10">
            <p>Autor: Gilmar Zezilia Alves</p>
            <p>Contato E-mail: <a href="mailto:Gilmaralve914@gmail.com"> GilmarAlves914@gmail.com.com</a></p>
        </div>`

**Comment by GilmarAlves99** [comment]
Obrigado, está corrigido !
